name: JadGens
version: '${project.version}'
main: dev.jadss.jadgens.JadGens
load: STARTUP
softdepend: [ JadAPI, PlayerPoints, Vault, PlaceholderAPI ]
authors: [ jadss ]
description: JadGens is a customizable machines plugin.
website: jadss.dev
commands:
  jadgens:
    usage: /<command>
    description: The Main command of jadgens!